log:
  level: ERROR
  filePath: /log/traefik.log
  format: json

accessLog:
  filePath: /log/access.log
  format: json

metrics:
  prometheus: {}

global:
  sendAnonymousUsage: false

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    endpoint: tcp://docker_socket_proxy:2375
    network: traefik
  file:
    filename: /etc/traefik/dynamic.yml

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      middlewares:
        - security-headers@file
        - gzip-compression@file

certificatesResolvers:
  letsencrypt:
    acme:
      email: webmaster@your-homelab-domain.de
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
