version: "3.9"

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    volumes:
      - ./services/homeassistant/conf:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  homebridge:
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - homebridge_data:/homebridge

volumes:
  homebridge_data: