version: "3.9"

services:
  fritz_exporter:
    image: pdreker/fritz_exporter:2
    restart: unless-stopped
    command: --config /fritz-exporter.yml
    volumes:
      - ./services/fritz-exporter/conf/fritz-exporter.yml:/fritz-exporter.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - monitoring
      - default
    labels:
      - "prometheus.job=fritz-exporter"
      - "prometheus.port=9100"
      - "prometheus.interval=120s"

  netatmo_exporter:
    image: xperimental/netatmo-exporter:1.5.1
    restart: unless-stopped
    environment: 
      - "NETATMO_EXPORTER_ADDR=:9100"
      - "NETATMO_CLIENT_ID=6### REDACTED ###"
      - "NETATMO_CLIENT_SECRET=### REDACTED ###"
      - "NETATMO_CLIENT_USERNAME=### REDACTED ###"
      - "NETATMO_CLIENT_PASSWORD=### REDACTED ###"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - monitoring
      - default
    labels:
      - "prometheus.job=netatmo-exporter"
      - "prometheus.port=9100"
      - "prometheus.interval=120s"

  speedtest_exporter:
    image: miguelndecarvalho/speedtest-exporter:v3.5.3
    restart: unless-stopped
    environment:
      - "SPEEDTEST_PORT=9100"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - monitoring
      - default
    labels:
      - "prometheus.job=speedtest-exporter"
      - "prometheus.port=9100"
      - "prometheus.interval=60m"
      - "prometheus.timeout=60s"

  node_exporter:
    image: prom/node-exporter:v1.5.0
    restart: unless-stopped
    environment:
      - "GOMAXPROCS=1"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.systemd"
      - "--collector.processes"
    volumes:
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - monitoring
      - default
    labels:
      - "prometheus.job=node-exporter"
      - "prometheus.port=9100"
      - "prometheus.interval=15s"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
    networks:
      - monitoring
      - default
    labels:
      - "prometheus.job=cadvisor"
      - "prometheus.port=8080"
      - "prometheus.interval=30s"

  prometheus:
    image: prom/prometheus:v2.42.0
    restart: unless-stopped
    volumes:
      - ./services/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - prometheus_data:/prometheus
    networks:
      - traefik
      - monitoring
      - docker_socket_proxy
      - default
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.your-homelab-domain.de`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.middlewares=only-internal-ips@file,auth@file"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:9.3.6
    restart: unless-stopped
    environment: 
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.strato.de:465"
      - "GF_SMTP_USER=webmaster@your-homelab-domain.de"
      - "GF_SMTP_PASSWORD=### REDACTED ###"
      - "GF_SMTP_FROM_ADDRESS=webmaster@your-homelab-domain.de"
      - "GF_SERVER_CERT_FILE=/var/lib/grafana/letsencrypt/certs/grafana.your-homelab-domain.de.crt"
      - "GF_SERVER_CERT_KEY=/var/lib/grafana/letsencrypt/private/grafana.your-homelab-domain.de.key"
      - "GF_SERVER_DOMAIN=grafana.your-homelab-domain.de"
      - "GF_SERVER_ENFORCE_DOMAIN=true"
      - "GF_USERS_ALLOW_SIGN_UP=true"
    depends_on:
      - prometheus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - grafana_data:/var/lib/grafana
      - letsencrypt_certs:/var/lib/grafana/letsencrypt:ro
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana.rule=Host(`grafana.your-homelab-domain.de`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.middlewares=only-internal-ips@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      
volumes:
  prometheus_data:
  grafana_data:
  letsencrypt_certs:
    external: true

networks:
  traefik:
    external: true
  monitoring:
    external: true
  docker_socket_proxy:
    external: true
  default:
    driver: bridge