version: "3.9"

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/traefik/conf:/etc/traefik
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - traefik_logs:/log
    networks:
      - traefik
      - monitoring
      - docker_socket_proxy
      - default
    extra_hosts:
      - host.docker.internal:172.17.0.1
      - fritzbox:192.168.178.1
    labels:
      - "prometheus.job=traefik"
      - "prometheus.port=8080"
      - "prometheus.interval=30s"

      - "traefik.enable=true"

      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.rule=Host(`traefik.your-homelab-domain.de`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=only-internal-ips@file,auth@file"
      - "traefik.http.routers.traefik.service=dashboard@internal"

      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.your-homelab-domain.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.entrypoints=websecure"
      - "traefik.http.routers.traefik-api.middlewares=only-internal-ips@file,auth@file"
      - "traefik.http.routers.traefik-api.service=api@internal"

  traefik_certs_dumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    restart: unless-stopped
    command: file --version v2 --watch --source /input/acme.json --dest /output
    depends_on:
      - traefik
    volumes:
      - ./services/traefik/conf:/input:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - letsencrypt_certs:/output

volumes:
  traefik_logs:
  letsencrypt_certs:
    external: true

networks:
  traefik:
    external: true
  monitoring:
    external: true
  docker_socket_proxy:
    external: true
  default:
    driver: bridge