global:
  evaluation_interval: 60s
  scrape_interval: 60s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: docker
    static_configs:
      - targets: ["172.17.0.1:9323"]
  - job_name: docker-containers
    docker_sd_configs:
      - host: tcp://docker_socket_proxy:2375
        refresh_interval: 60s
    relabel_configs:
      - source_labels: [__meta_docker_network_name]
        regex: monitoring
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        target_label: job
      - source_labels: [__meta_docker_container_label_prometheus_interval]
        action: replace
        target_label: __scrape_interval__
        regex: (.+)
      - source_labels: [__meta_docker_container_label_prometheus_timeout]
        action: replace
        target_label: __scrape_timeout__
        regex: (.+)
      - source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        target_label: __address__
        action: replace
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
  - job_name: minio
    scrape_interval: 60s
    bearer_token: ### REDACTED ###
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio:9000"]