{
 "title": "AdGuard",
 "tags": [ "networking" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(adguard_num_dns_queries, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Percent of queries blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_avg_processing_time{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_protection_enabled{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "adguard_top_queried_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}