{
 "title": "Netatmo Weather Station",
 "tags": [
  "weather",
  "iot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RF Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "-netatmo_sensor_rf_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "-netatmo_sensor_wifi_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "netatmo_sensor_battery_percent", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "netatmo_sensor_humidity_percent",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "netatmo_sensor_co2_ppm", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    { "expr": "netatmo_sensor_pressure_mb", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "netatmo_sensor_noise_db", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Rain Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    { "expr": "netatmo_sensor_rain_amount_mm", "legendFormat": "{{module}}" }
   ]
  }
 ]
}